-- Vocabulary captured by each user.
--
-- `id` is generated by the client so a word created offline keeps one identity
-- across every device. The primary key is therefore not enough to authorise a
-- write: every query is additionally scoped by `user_id`, and the sync upsert
-- refuses to update a row owned by somebody else.
CREATE TABLE IF NOT EXISTS words (
    id                UUID        PRIMARY KEY,
    user_id           UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,

    word              TEXT        NOT NULL,
    meaning           TEXT        NOT NULL,
    pronunciation     TEXT,
    part_of_speech    TEXT,
    source            TEXT,
    examples          JSONB       NOT NULL DEFAULT '[]'::jsonb,
    tags              JSONB       NOT NULL DEFAULT '[]'::jsonb,

    -- The day the word was captured, as the user experienced it.
    day               DATE        NOT NULL,

    -- Tombstone. Deleted rows are retained so the deletion can propagate to
    -- other devices, which would otherwise re-upload the word.
    is_deleted        BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Client clock. Used for last-write-wins conflict resolution only.
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL,

    -- Server clock. This is the pull cursor: a client's own clock may be
    -- skewed or wrong, and ordering the change feed by `updated_at` would let
    -- a row with a past timestamp slip in behind a cursor that already moved.
    server_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_words_word_not_blank CHECK (length(btrim(word)) > 0)
);

-- Drives the incremental pull.
CREATE INDEX IF NOT EXISTS idx_words_user_cursor
    ON words (user_id, server_updated_at);

-- Drives per-day listing.
CREATE INDEX IF NOT EXISTS idx_words_user_day
    ON words (user_id, day DESC)
    WHERE is_deleted = FALSE;
