use std::future::Future;

use chrono::{DateTime, Utc};
use uuid::Uuid;

use crate::domain::vocabulary::entities::word::Word;

/// A word together with the server-side cursor value it was stored at.
#[derive(Debug, Clone)]
pub struct WordChange {
    pub word: Word,
    /// Server clock. The client uses the highest value it has seen as the
    /// cursor for its next pull.
    pub server_updated_at: DateTime<Utc>,
}

/// Port for vocabulary persistence.
///
/// Every method takes `user_id` explicitly: word ids are generated by clients,
/// so ownership can never be inferred from the id alone.
pub trait WordRepository: Send + Sync {
    /// Applies a batch of client changes, resolving conflicts by
    /// last-write-wins on `updated_at`.
    ///
    /// Returns the ids that were accepted. Ids omitted from the result were
    /// rejected — either stale, or owned by another user.
    fn upsert_batch(
        &self,
        user_id: Uuid,
        words: &[Word],
    ) -> impl Future<Output = Result<Vec<Uuid>, anyhow::Error>> + Send;

    /// Words whose server cursor is strictly after `since`, oldest first.
    ///
    /// Includes tombstones so deletions propagate. `None` means a full sync.
    fn changes_since(
        &self,
        user_id: Uuid,
        since: Option<DateTime<Utc>>,
        limit: i64,
    ) -> impl Future<Output = Result<Vec<WordChange>, anyhow::Error>> + Send;

    /// A page of the user's live vocabulary, newest day first.
    fn list(
        &self,
        user_id: Uuid,
        offset: i64,
        limit: i64,
    ) -> impl Future<Output = Result<(Vec<Word>, u64), anyhow::Error>> + Send;

    fn find_by_id(
        &self,
        user_id: Uuid,
        id: Uuid,
    ) -> impl Future<Output = Result<Option<Word>, anyhow::Error>> + Send;
}
