use chrono::{DateTime, NaiveDate, Utc};
use uuid::Uuid;

use crate::domain::vocabulary::value_objects::part_of_speech::PartOfSpeech;
use crate::domain::vocabulary::value_objects::word_text::{OptionalText, WordText};

/// A vocabulary entry owned by one user.
///
/// The aggregate is deliberately small and carries no domain events: capturing
/// a word is a private note, not something other contexts react to. If that
/// changes, events would be raised here and drained through the outbox exactly
/// as the identity context does.
#[derive(Debug, Clone)]
pub struct Word {
    /// Generated by the client so a word created offline keeps one identity
    /// across devices.
    pub id: Uuid,
    pub user_id: Uuid,

    pub word: WordText,
    pub meaning: WordText,
    pub pronunciation: OptionalText,
    pub part_of_speech: Option<PartOfSpeech>,
    pub source: OptionalText,
    pub examples: Vec<String>,
    pub tags: Vec<String>,

    /// The day the user captured the word.
    pub day: NaiveDate,

    /// Tombstone. Retained so the deletion reaches other devices.
    pub is_deleted: bool,

    /// Client clocks, used only for last-write-wins resolution.
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Word {
    /// Maximum number of example sentences or tags accepted on one word.
    ///
    /// Bounded so a single row cannot grow without limit.
    pub const MAX_LIST_ITEMS: usize = 25;

    /// Longest accepted example sentence or tag.
    pub const MAX_ITEM_LEN: usize = 1024;

    #[allow(clippy::too_many_arguments)]
    pub fn reconstitute(
        id: Uuid,
        user_id: Uuid,
        word: WordText,
        meaning: WordText,
        pronunciation: OptionalText,
        part_of_speech: Option<PartOfSpeech>,
        source: OptionalText,
        examples: Vec<String>,
        tags: Vec<String>,
        day: NaiveDate,
        is_deleted: bool,
        created_at: DateTime<Utc>,
        updated_at: DateTime<Utc>,
    ) -> Self {
        Self {
            id,
            user_id,
            word,
            meaning,
            pronunciation,
            part_of_speech,
            source,
            examples,
            tags,
            day,
            is_deleted,
            created_at,
            updated_at,
        }
    }

    /// Whether `incoming` should replace this word.
    ///
    /// Last-write-wins on the client clock. Ties keep the stored row so a
    /// retried upload is a no-op rather than a pointless write.
    pub fn is_superseded_by(&self, incoming: &Word) -> bool {
        incoming.updated_at > self.updated_at
    }

    /// Normalises and bounds a list of example sentences or tags.
    ///
    /// Blank entries are dropped and the list is truncated rather than
    /// rejected: a client that sends slightly too much should still sync.
    pub fn normalise_list(values: Vec<String>) -> Vec<String> {
        values
            .into_iter()
            .map(|value| value.trim().to_string())
            .filter(|value| !value.is_empty())
            .map(|mut value| {
                if value.chars().count() > Self::MAX_ITEM_LEN {
                    value = value.chars().take(Self::MAX_ITEM_LEN).collect();
                }
                value
            })
            .take(Self::MAX_LIST_ITEMS)
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn word_at(updated_at: DateTime<Utc>) -> Word {
        Word::reconstitute(
            Uuid::nil(),
            Uuid::nil(),
            WordText::new("resilient").unwrap(),
            WordText::new("kiên cường").unwrap(),
            OptionalText::default(),
            None,
            OptionalText::default(),
            vec![],
            vec![],
            NaiveDate::from_ymd_opt(2026, 8, 18).unwrap(),
            false,
            updated_at,
            updated_at,
        )
    }

    #[test]
    fn a_newer_write_supersedes_an_older_one() {
        let stored = word_at(Utc::now());
        let incoming = word_at(stored.updated_at + chrono::Duration::seconds(1));
        assert!(stored.is_superseded_by(&incoming));
    }

    #[test]
    fn an_older_write_does_not_supersede() {
        let stored = word_at(Utc::now());
        let incoming = word_at(stored.updated_at - chrono::Duration::seconds(1));
        assert!(!stored.is_superseded_by(&incoming));
    }

    #[test]
    fn an_identical_timestamp_is_treated_as_a_replay() {
        let stored = word_at(Utc::now());
        let incoming = word_at(stored.updated_at);
        assert!(!stored.is_superseded_by(&incoming));
    }

    #[test]
    fn list_normalisation_drops_blanks_and_trims() {
        let result = Word::normalise_list(vec![
            "  a sentence  ".to_string(),
            "   ".to_string(),
            String::new(),
        ]);
        assert_eq!(result, vec!["a sentence".to_string()]);
    }

    #[test]
    fn list_normalisation_bounds_the_length() {
        let values = (0..Word::MAX_LIST_ITEMS + 10)
            .map(|i| i.to_string())
            .collect();
        assert_eq!(Word::normalise_list(values).len(), Word::MAX_LIST_ITEMS);
    }

    #[test]
    fn list_normalisation_truncates_an_overlong_item() {
        let long = "x".repeat(Word::MAX_ITEM_LEN + 50);
        let result = Word::normalise_list(vec![long]);
        assert_eq!(result[0].chars().count(), Word::MAX_ITEM_LEN);
    }
}
